---
- name: Use Expect
  hosts: 127.0.0.1
  connection: local
  gather_facts: false

  vars:
    jks_password: "{{ jkspassword }}"

  tasks:
    - name: install expect
      pip: name=pexpect
      
    - name: Generate JKS file
      expect:
       command: keytool -genkeypair -alias jboss -keyalg RSA -keystore keystore.jks -storepass mykeystorepass --dname "CN=jsmith,OU=Engineering,O=mycompany.com,L=Raleigh,S=NC,C=US"
       responses:
         Enter key password for \<jboss\>\r\n\t\(RETURN if same as keystore password\): "{{ jks_password }}"
         Re-enter new password: "{{ jks_password }}" 
         Enter source keystore password: "{{ jks_password }}"