cxf:
  path: /rest
jbpm:
  executor:
    enabled: false
kieserver:
  casemgmt:
    enabled: true
  dmn:
    enabled: true
  drools:
    enabled: true
  jbpm:
    enabled: true
  jbpmui:
    enabled: true
  location: http://localhost:8090/rest/server
  serverId: business-application-service
  serverName: business-application-service
server:
  address: 0.0.0.0
  port: 8090
spring:
  banner:
    location: classpath:banner.txt
  datasource:
    driver-class-name: org.h2.Driver
    password: sa
    url: jdbc:h2:./target/spring-boot-jbpm
    username: sa
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: update
        show_sql: false
  jta:
    narayana:
      transaction-manager-id: 1

# Define KJARs to deploy here
deployment:
  kjars:
    - alias: kie-sboot-test-kjar
      artifactId: example-process-kjar
      containerId: kie-sboot-test-kjar-1_0-SNAPSHOT
      groupId: org.redhat.services
      version: 0.0.1-SNAPSHOT

logging:
  level:
    org.eclipse: TRACE
