name: Build for  pam-eap-setup

on:
  push:
    paths:
      - .github/workflows/build-deployment-examples.yaml
      - deployment-examples/pam-eap-setup/**
  pull_request:
    paths:
      - .github/workflows/build-deployment-examples.yaml
      - deployment-examples/pam-eap-setup/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    steps:
      - name: Support longpaths
        if: matrix.os == 'windows-latest'
        run: git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@v4

      - name: redhat-csp-download
        if: matrix.os == 'ubuntu-latest'
        uses: redhat-cop/github-actions/redhat-csp-download@master
        with:
          rh_username: ${{ secrets.RH_USERNAME }}
          rh_password: ${{ secrets.RH_PASSWORD }}
          download: '[{"file":"/github/workspace/jboss-eap-7.3.0.zip","url":"https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId=80101"},{"file":"/github/workspace/jboss-eap-7.3.3-patch.zip","url":"https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId=88471"},{"file":"/github/workspace/rhpam-7.9.0-business-central-eap7-deployable.zip","url":"https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId=89691"},{"file":"/github/workspace/rhpam-7.9.0-kie-server-ee8.zip","url":"https://access.redhat.com/jbossnetwork/restricted/softwareDownload.html?softwareId=89701"}]'

      - name: Run pam-setup.sh
        if: matrix.os == 'ubuntu-latest'
        uses: ./.github/actions/eap-base
        with:
          should_run: ${{ secrets.RH_USERNAME }}
          command: "cd deployment-examples/pam-eap-setup; ./pam-setup.sh; rm -rf pam"

      - name: Run ShellCheck
        if: matrix.os == 'ubuntu-latest'
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error
          ignore: bcgithook bdd-ui kogito-quick-start-workshop offliner-maven-plugin pam-quick-examples pam-vagrant rhpam-charts
