# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven for Extras folder

on:
  push:
    paths:
      - .github/workflows/mvn-extras.yaml
      - extras/**
  pull_request:
    paths:
      - .github/workflows/mvn-extras.yaml
      - extras/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Support longpaths
        if: matrix.os == 'windows-latest'
        run: git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 8.0
          distribution: temurin

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-extras
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: '[{ "id": "redhat-ga-repository", "url": "https://maven.repository.redhat.com/ga/", "releases": {"enabled":"true"} }]'
          plugin_repositories: '[{ "id": "redhat-ga-repository", "url": "https://maven.repository.redhat.com/ga" }]'

      - name: Run ShellCheck
        if: matrix.os == 'ubuntu-latest'
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error
          ignore: bcgithook bdd-ui kogito-quick-start-workshop offliner-maven-plugin pam-eap-setup pam-quick-examples pam-vagrant rhpam-charts

      - name: Build offliner-maven-plugin
        run: |
          pushd extras/offliner-maven-plugin
          mvn -B clean package --no-transfer-progress
          popd

      # Jave 11 Builds
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: '[{ "id": "redhat-ga-repository", "url": "https://maven.repository.redhat.com/ga/", "releases": {"enabled":"true"} }]'
          plugin_repositories: '[{ "id": "redhat-ga-repository", "url": "https://maven.repository.redhat.com/ga" }]'

      - name: Build extras/task-automator
        run: |
          pushd extras/task-automator
          mvn -B clean package --no-transfer-progress
          popd
      
      - name: Build extras/data-generator
        run: |
          pushd extras/data-generator
          mvn -B clean package --no-transfer-progress
          popd
