# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven for coded-examples

on:
  push:
    paths:
      - .github/workflows/mvn-coded-examples.yaml
      - coded-examples/**
  pull_request:
    paths:
      - .github/workflows/mvn-coded-examples.yaml
      - coded-examples/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Support longpaths
        if: matrix.os == 'windows-latest'
        run: git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 8.0
          distribution: temurin

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-coded-examples
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: '[{ "id": "redhat-ga-repository", "url": "https://maven.repository.redhat.com/ga" }]'
          plugin_repositories: '[{ "id": "redhat-ga-repository", "url": "https://maven.repository.redhat.com/ga" }]'

      - name: Run ShellCheck
        if: matrix.os == 'ubuntu-latest'
        uses: ludeeus/action-shellcheck@master
        with:
          ignore: bcgithook bdd-ui kogito-quick-start-workshop offliner-maven-plugin pam-eap-setup pam-vagrant rhpam-charts

      - name: Build coded-examples
        run: |
          pushd coded-examples/dmn-examples
          mvn -B install --no-transfer-progress
          popd

          pushd coded-examples/business-central
          mvn -B install --no-transfer-progress
          popd
          
          pushd coded-examples/spring-boot-examples
          mvn -B install --no-transfer-progress
          popd

          pushd coded-examples/kie-server-extensions
          mvn -B install --no-transfer-progress
          popd

          pushd coded-examples/quarkus-examples
          mvn -B install --no-transfer-progress
          popd

          pushd coded-examples/spring-boot-examples/jms/start-jms
          mvn -B install --no-transfer-progress
          popd
