# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven for workshops

on:
  push:
    paths:
      - .github/workflows/mvn-workshops.yaml
      - workshops/**
  pull_request:
    paths:
      - .github/workflows/mvn-workshops.yaml
      - workshops/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Support longpaths
        if: matrix.os == 'windows-latest'
        run: git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 8.0
          distribution: temurin

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-kogito-quick-start-workshop
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build workshops/kogito-quick-start-workshop
        run: |
          pushd workshops/kogito-quick-start-workshop
          mvn -B clean install -f apps/barista/pom.xml --no-transfer-progress --no-transfer-progress
          mvn -B clean install -f apps/coffee-shop/pom.xml --no-transfer-progress
          popd
