name: Java CI with Maven for deployment-examples

on:
  push:
    paths:
      - .github/workflows/mvn-deployment-examples-rhpam-charts.yaml
      - deployment-examples/rhpam-charts/**
  pull_request:
    paths:
      - .github/workflows/mvn-deployment-examples-rhpam-charts.yaml
      - deployment-examples/rhpam-charts/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Support longpaths
        if: matrix.os == 'windows-latest'
        run: git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          java-version: 8.0
          distribution: temurin

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-deployment-examples-rhpam-charts
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: '[{ "id": "redhat-ga-repository", "url": "https://maven.repository.redhat.com/ga" }]'
          plugin_repositories: '[{ "id": "redhat-ga-repository", "url": "https://maven.repository.redhat.com/ga" }]'

#      - name: Run ShellCheck
#        if: matrix.os == 'ubuntu-latest'
#        uses: ludeeus/action-shellcheck@master
#        env:
#          SHELLCHECK_OPTS: -e SC3043 -e SC2086 -e SC2112 -e SC3059 -e SC2034 -e SC1072 -e SC1056 -e SC1073 -e SC1054 -e SC2068 

#        with:
#          ignore: bcgithook bdd-ui kogito-quick-start-workshop offliner-maven-plugin pam-eap-setup pam-vagrant rhpam-charts

# Example Mvn Build 
      # - name: Build deployment-examples/<NEW_PROJECT>
      #   run: |
      #     pushd deployment-examples/<NEW_PROJECT>
      #     mvn -B clean package --no-transfer-progress
      #     popd
